### PR TITLE
Adding fontawesome icons.

### PR DESCRIPTION
**Pull request by computate**

### CODE REVIEW

**Comment by ralphbean** [comment]
I think my only question is about https://fontawesome.com/license

@mairin do you know if we run afoul there by our usage here?

**Comment by computate** [comment]
As I am a fontawesome pro subscriber, I'm able to make it usable on  rh-impact.github.io

Here is what I understand, which is "You can download and use Font Awesome Pro for as long as you like on as many web, print, and mobile projects you would like"
What does a Font Awesome Pro License get me?

Subscribing to a Pro-level Plan that includes a Font Awesome Pro license gets you the following…
Perpetual Use of Font Awesome Pro

You can download and use Font Awesome Pro for as long as you like on as many web, print, and mobile projects you would like for the versions of Font Awesome released during your subscription.
A year's subscription to all of services and features included in your Pro plan.

This includes Kits, Pro CDN, our private NPM repository for Pro, and any other services we develop.
A year's subscription of updates to Font Awesome Pro itself.

You get the latest versions and updates to all our icons, styles, services, and tools.

**Comment by computate** [comment]
We use the Font Awesome CDN with the link they provide me: 
```
<link rel="stylesheet" href="https://pro.fontawesome.com/releases/v5.15.4/css/all.css" integrity="sha384-rqn26AG5Pj86AF4SO72RK5fyefcQ/x32DNQfChxWvbXIyXFePlEktwD18fEz+kQU" crossorigin="anonymous">
```
And this is not redistributing the fontawesome assets or fontawesome source code. It's able to pull down the icons because the referrer of the request checks that the rh-impact.github.io site is in the approved domains that I specify in my account with fontawesome.

**Comment by mairin** [comment]
I'm not sure. I know we use the free ones within Patternfly and that's been vetted AFAIK.

**Comment by ralphbean** [comment]
From https://fontawesome.com/license#license I found https://fontawesome.com/license#what-creators-may-not-do which contains:

> Pass on Permission to Embed
> Creators may not give non-Creators permission to Embed Pro Icons in new Projects of their own, or to Embed them in Projects in new ways.

So, I am not a lawyer and this does not consitute legal advice, but my reading of this is that @computate is allowed to embed pro icons in new projects (like this one), but he is not allowed to allow me to embed pro icons in new projects.

**Comment by ralphbean** [comment]
>  @computate is allowed to embed pro icons in new projects (like this one)

I think that means we are ok here and this is good to merge.

**Pull request merged**
